version: "3.1"

volumes:
  ts-express-sample-redis-volume:

services:
  redis:
    image: redis:alpine
    container_name: ts-express-sample-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - ts-express-sample-redis-volume:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master